### ISSUE TITLE
datasette.simonwillison.net

### ISSUE THREAD

**Issue by simonw** [simonw/simonwillisonblog#273]
Initially so I can demonstrate `sqlite-comprehend` but I want this for other future demos too.

I'm going to run it from https://github.com/simonw/simonwillisonblog-backup

**Comment by simonw** [comment]
I'm going to publish to Cloud Run with the `datasette-block-robots` plugin.

**Comment by simonw** [comment]
The usual Cloud Run pattern is:

```yaml
    - name: Set up Cloud Run
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: '275.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Deploy to Cloud Run
      run: |-
        gcloud config set run/region us-central1
        gcloud config set project datasette-222320
        datasette publish cloudrun covid.db simonwillisonblog.db \
          --service simonwillisonblog \
          -m metadata.json
```
