### ISSUE TITLE
Backups fail to deploy latest version to Cloud Run

### ISSUE THREAD

**Issue by simonw** [simonw/simonwillisonblog#359]
I've noticed that this mechanism https://github.com/simonw/simonwillisonblog-backup always seems to backup the latest version to Git, but then deploys a Cloud Run instance with the previous version, without the latest changes.

**Comment by simonw** [comment]
Spotted why: https://github.com/simonw/simonwillisonblog-backup/blob/628d17b898a5b3bb5641831f6823fa95404d0c73/.github/workflows/backup.yml

The problem is that the first step commits the changes, then the second step starts like this:

```yaml
  build_and_deploy:
    runs-on: ubuntu-latest
    needs: backup
    if: ${{ inputs.force_deploy || needs.backup.outputs.change_detected }}
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
```
But from this log https://github.com/simonw/simonwillisonblog-backup/actions/runs/5648496825/job/15300872394

I see:
```
/usr/bin/git log -1 --format='%H'
'e37de4e52533be2f99d055db94ce201a6d4ea59e'
```
Clearly this step here is checking out the commit that triggered the run, not the most recent commit to `main`:
```
 /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +e37de4e52533be2f99d055db94ce201a6d4ea59e:refs/remotes/origin/main
```
