### ISSUE TITLE
Reduce gaps between paragraphs in blogmarks

### ISSUE THREAD

**Issue by simonw** [simonw/simonwillisonblog#393]
These gaps are too big:

![CleanShot 2024-01-08 at 13 56 48@2x](https://github.com/simonw/simonwillisonblog/assets/9599/6ef56c8f-a385-4785-b4c5-b81deb3ba8fd)

The problem is I'm using double-br for these at the moment, and switching to proper paragraphs is a slightly bigger change. See also:
- #74

**Comment by simonw** [comment]
This trick works:

```css
.blogmark br {
    display: block;
    line-height: 0;
    margin-bottom: 0.3em;
}
```
