### ISSUE TITLE
Spacing on tag archive page is messed up

### ISSUE THREAD

**Issue by simonw** [simonw/simonwillisonblog#395]
https://simonwillison.net/tags/gpt4/

![CleanShot 2024-01-09 at 15 55 26@2x](https://github.com/simonw/simonwillisonblog/assets/9599/894b7c99-2fa6-4add-b66a-6be7be6ed525)

Related:
- #393 
- #394

**Comment by simonw** [comment]
That fixed the blogmark display: https://simonwillison.net/tags/gpt4/

![CleanShot 2024-01-09 at 16 02 21@2x](https://github.com/simonw/simonwillisonblog/assets/9599/02dc869e-4d6e-46d1-a279-912aababaa22)

I'm going to use that previous `<br>` hack for quotes:

```css
 {
  display: block;
  line-height: 0;
  margin-bottom: 0.3em;
}
```
