### ISSUE TITLE
Support for markdown in quotations

### ISSUE THREAD

**Issue by simonw** [simonw/simonwillisonblog#451]
I'm not going to have a boolean flag for enabling this (like I did for blogmarks) - I'm just going to turn on markdown for all paragraphs.

Need to avoid breaking any existing ones though.

**Comment by simonw** [comment]
Here are the 24 quotes that, when rendered as Markdown, have HTML elements in other than paragraphs: https://static.simonwillison.net/static/2024/quotations-to-fix.html

I'll fix those manually after shipping this.

**Comment by simonw** [comment]
```python
from blog.models import Quotation
from markdown import markdown
import re
rendered = []
for q in Quotation.objects.all():
    rendered.append((q, markdown(q.quotation)))

contains_other_tags = lambda s: bool(re.search(r'<(?!/?p\b)[^>]+>', s))

differ = [r for r in rendered if '<p>' + r[0].quotation + '</p>' != r[1]]
interesting = [r for r in differ if contains_other_tags(r[1])]
all_html_i = '\n<hr>\n'.join([
    r[1] + '<a href="https://simonwillison.net/q/' + str(r[0].pk) + '">#</a>'
    for r in interesting
])

# Trick to copy the data out of my Heroku terminal session by double clicking it:
print('\n\n\n\n' + base64.b64encode(all_html_i.encode()).decode())
```
Then locally, save that to `i.txt` and run:
```bash
cat i.txt | base64 -d > i.html
```

**Comment by simonw** [comment]
Styling problem with multiple paragraph quotes (now we use `<p>` instead of `<br><br>` for those):

![CleanShot 2024-06-24 at 07 46 35@2x](https://github.com/simonw/simonwillisonblog/assets/9599/c3f8d66f-0352-418e-b3db-e890386ef069)

FIx is to add the `:last-child` selector here:

```css
div#primary div.quote blockquote p:last-child {
  background-image: url(/static/css/img/rquo.png);
  background-size: 18px 13px;
  background-repeat: no-repeat;
  background-position: bottom 3px right;
  padding-right: 23px;
  display: inline;
}
```
Now it looks like this:

![CleanShot 2024-06-24 at 07 47 41@2x](https://github.com/simonw/simonwillisonblog/assets/9599/189b7ec1-735a-4a42-bc64-be26554df707)

**Comment by simonw** [comment]
I identified these that I needed to manually fix, and fixed them:

- https://simonwillison.net/2024/Apr/29/tailscalecominstallsh/
- https://simonwillison.net/2023/Oct/2/ynik/
-

**Comment by simonw** [comment]
Second paragraph here should not be indented:

![CleanShot 2024-06-24 at 07 53 05@2x](https://github.com/simonw/simonwillisonblog/assets/9599/05cb26eb-9ce6-484d-81e9-cf6a7c5f837a)

**Comment by simonw** [comment]
And fix bullet styling here: https://simonwillison.net/2020/Jul/20/adam-nash/

![CleanShot 2024-06-24 at 07 54 03@2x](https://github.com/simonw/simonwillisonblog/assets/9599/e2cee1a6-9da9-4ec3-8534-1226edd895e7)

**Comment by simonw** [comment]
Fixing the three paragraph case is harder because the LAST paragraph is already `display: inline` to get the closing paragraph to show in the right place - but if you do that to the FIRST paragraph it loses its text indent if the text indent is applied to the paragraph and not the blockquote.

So for a single paragraph quotation we need it to be inline (for the closing one) but also indented (for the opening one).

**Comment by simonw** [comment]
Found a devious fix for that:
```css
/* The text-indent is ignored on the first paragraph if it
is also the last paragraph (because it is inline), so in
the case where there is only one contained paragraph we
indent the blockquote itself. */
div#primary div.quote blockquote:has(p:only-child),
div#primary div.quote blockquote p:first-child {
  text-indent: 23px;
}
```
