### ISSUE TITLE
Max width on images in blogmarks

### ISSUE THREAD

**Issue by simonw** [simonw/simonwillisonblog#457]
Oops:

![CleanShot 2024-07-03 at 12 30 11@2x](https://github.com/simonw/simonwillisonblog/assets/9599/822728f6-6f97-412f-a1f5-74fb2946f7f2)

I should apply this:
```css
.entry img,
.blogmark img {
    max-width: 100%;
}
```
